"""initial_schema

Revision ID: df6223b6242d
Revises: 
Create Date: 2026-05-01 23:52:48.408766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df6223b6242d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametro_i18n')
    op.drop_table('sub_variedad_i18n')
    op.drop_table('variedad_i18n')
    op.drop_constraint('analisis_muestra_id_fkey', 'analisis', type_='foreignkey')
    op.create_foreign_key(None, 'analisis', 'muestra', ['muestra_id'], ['muestra_id'])
    op.drop_constraint('analisis_especial_lote_id_fkey', 'analisis_especial', type_='foreignkey')
    op.create_foreign_key(None, 'analisis_especial', 'lote', ['lote_id'], ['lote_id'])
    op.alter_column('analisis_fuente_imagen', 'tamano_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'analisis_fuente_imagen', 'analisis', ['analisis_id'], ['analisis_id'])
    op.create_foreign_key(None, 'analisis_fuente_imagen', 'usuario', ['updated_by'], ['user_id'])
    op.create_foreign_key(None, 'analisis_fuente_imagen', 'usuario', ['created_by'], ['user_id'])
    op.drop_constraint('uq_analisis_resultado_analisis_parametro', 'analisis_resultado', type_='unique')
    op.drop_constraint('analisis_resultado_analisis_id_fkey', 'analisis_resultado', type_='foreignkey')
    op.create_foreign_key(None, 'analisis_resultado', 'analisis', ['analisis_id'], ['analisis_id'])
    op.drop_index('idx_ari_analisis_id_parametro_id', table_name='analisis_resultado_ia')
    op.drop_constraint('evidencia_muestra_id_fkey', 'evidencia', type_='foreignkey')
    op.create_foreign_key(None, 'evidencia', 'muestra', ['muestra_id'], ['muestra_id'])
    op.create_foreign_key(None, 'evidencia', 'usuario', ['deleted_by'], ['user_id'])
    op.alter_column('evidencia_especial', 'tipo',
               existing_type=postgresql.ENUM('foto', 'video', name='evidencia_tipo'),
               type_=sa.Enum('foto', 'video', 'documento', name='evidencia_especial_tipo'),
               existing_nullable=False)
    op.drop_constraint('evidencia_especial_analisis_especial_id_fkey', 'evidencia_especial', type_='foreignkey')
    op.create_foreign_key(None, 'evidencia_especial', 'analisis_especial', ['analisis_especial_id'], ['analisis_especial_id'])
    op.drop_constraint('ficha_reporte_muestra_id_fkey', 'ficha_reporte', type_='foreignkey')
    op.create_foreign_key(None, 'ficha_reporte', 'muestra', ['muestra_id'], ['muestra_id'])
    op.drop_constraint('ficha_reporte_invitado_ficha_id_fkey', 'ficha_reporte_invitado', type_='foreignkey')
    op.create_foreign_key(None, 'ficha_reporte_invitado', 'ficha_reporte', ['ficha_id'], ['ficha_id'])
    op.add_column('lote_documento', sa.Column('status', sa.Enum('activo', 'archivado', 'eliminado', name='lote_documento_status'), nullable=False))
    op.alter_column('lote_documento', 'tamano_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_lote_documento_updated_by', table_name='lote_documento')
    op.drop_column('lote_documento', 'estado')
    op.alter_column('lote_muestra_fuente_imagen_ia', 'tamano_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('muestra_lote_id_fkey', 'muestra', type_='foreignkey')
    op.create_foreign_key(None, 'muestra', 'lote', ['lote_id'], ['lote_id'])
    op.alter_column('plantilla_analisis', 'plantilla_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('plantilla_analisis_nombre_version_key', 'plantilla_analisis', type_='unique')
    op.alter_column('usuario', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_usuario_telefono', table_name='usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_usuario_telefono', 'usuario', ['telefono'], unique=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.String(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_unique_constraint('plantilla_analisis_nombre_version_key', 'plantilla_analisis', ['nombre', 'version'])
    op.alter_column('plantilla_analisis', 'plantilla_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'muestra', type_='foreignkey')
    op.create_foreign_key('muestra_lote_id_fkey', 'muestra', 'lote', ['lote_id'], ['lote_id'], ondelete='CASCADE')
    op.alter_column('lote_muestra_fuente_imagen_ia', 'tamano_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.add_column('lote_documento', sa.Column('estado', postgresql.ENUM('activo', 'archivado', 'eliminado', name='lote_documento_status'), server_default=sa.text("'activo'::lote_documento_status"), autoincrement=False, nullable=False))
    op.create_index('idx_lote_documento_updated_by', 'lote_documento', ['updated_by'], unique=False)
    op.alter_column('lote_documento', 'tamano_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('lote_documento', 'status')
    op.drop_constraint(None, 'ficha_reporte_invitado', type_='foreignkey')
    op.create_foreign_key('ficha_reporte_invitado_ficha_id_fkey', 'ficha_reporte_invitado', 'ficha_reporte', ['ficha_id'], ['ficha_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ficha_reporte', type_='foreignkey')
    op.create_foreign_key('ficha_reporte_muestra_id_fkey', 'ficha_reporte', 'muestra', ['muestra_id'], ['muestra_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'evidencia_especial', type_='foreignkey')
    op.create_foreign_key('evidencia_especial_analisis_especial_id_fkey', 'evidencia_especial', 'analisis_especial', ['analisis_especial_id'], ['analisis_especial_id'], ondelete='CASCADE')
    op.alter_column('evidencia_especial', 'tipo',
               existing_type=sa.Enum('foto', 'video', 'documento', name='evidencia_especial_tipo'),
               type_=postgresql.ENUM('foto', 'video', name='evidencia_tipo'),
               existing_nullable=False)
    op.drop_constraint(None, 'evidencia', type_='foreignkey')
    op.drop_constraint(None, 'evidencia', type_='foreignkey')
    op.create_foreign_key('evidencia_muestra_id_fkey', 'evidencia', 'muestra', ['muestra_id'], ['muestra_id'], ondelete='CASCADE')
    op.create_index('idx_ari_analisis_id_parametro_id', 'analisis_resultado_ia', ['analisis_id', 'parametro_id'], unique=False)
    op.drop_constraint(None, 'analisis_resultado', type_='foreignkey')
    op.create_foreign_key('analisis_resultado_analisis_id_fkey', 'analisis_resultado', 'analisis', ['analisis_id'], ['analisis_id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_analisis_resultado_analisis_parametro', 'analisis_resultado', ['analisis_id', 'parametro_id'])
    op.drop_constraint(None, 'analisis_fuente_imagen', type_='foreignkey')
    op.drop_constraint(None, 'analisis_fuente_imagen', type_='foreignkey')
    op.drop_constraint(None, 'analisis_fuente_imagen', type_='foreignkey')
    op.alter_column('analisis_fuente_imagen', 'tamano_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'analisis_especial', type_='foreignkey')
    op.create_foreign_key('analisis_especial_lote_id_fkey', 'analisis_especial', 'lote', ['lote_id'], ['lote_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'analisis', type_='foreignkey')
    op.create_foreign_key('analisis_muestra_id_fkey', 'analisis', 'muestra', ['muestra_id'], ['muestra_id'], ondelete='CASCADE')
    op.create_table('variedad_i18n',
    sa.Column('variedad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variedad_id'], ['variedad.variedad_id'], name='variedad_i18n_variedad_fk'),
    sa.PrimaryKeyConstraint('variedad_id', 'lang', name='variedad_i18n_pkey')
    )
    op.create_table('sub_variedad_i18n',
    sa.Column('sub_variedad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sub_variedad_id'], ['sub_variedad.sub_variedad_id'], name='sub_variedad_i18n_sub_variedad_fk'),
    sa.PrimaryKeyConstraint('sub_variedad_id', 'lang', name='sub_variedad_i18n_pkey')
    )
    op.create_table('parametro_i18n',
    sa.Column('parametro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parametro_id'], ['parametro.parametro_id'], name='parametro_i18n_parametro_fk'),
    sa.PrimaryKeyConstraint('parametro_id', 'lang', name='parametro_i18n_pkey')
    )
    # ### end Alembic commands ###
